### ISSUE TITLE
Source Code for executable file?

### ISSUE THREAD

**Issue by esklarski** [newjoker6/Godot-System-Tray#2]
I'm looking to add this same functionality to my project, and wondering if you're planning to share the source code for the executable to help guide others?

I'm also unwilling to consider shipping binaries I do not have any ability to check for safety issues.

And and and, I'd like to expand this functionality to other OS's 😁

**Comment by newjoker6** [comment]
[main.zip](https://github.com/newjoker6/Godot-System-Tray/files/15153231/main.zip)
